"""Add role field to users

Revision ID: 823d4de98ea3
Revises: 96ea5a4f669e
Create Date: 2025-07-28 05:20:38.599853

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '823d4de98ea3'
down_revision: Union[str, Sequence[str], None] = '96ea5a4f669e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    user_role_enum = sa.Enum("USER", "ADMIN", name="user_role")
    user_role_enum.create(op.get_bind(), checkfirst=True)

    op.add_column(
        "users",
        sa.Column("role", user_role_enum, server_default="USER", nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'role')
    user_role_enum = sa.Enum('USER', 'ADMIN', name='user_role')
    user_role_enum.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
